SAST/README.md, SAST/bitbucket-mend_sast.yml
Migrated the changes suggested by @tabac-ws in whitesource-ft [PR 113](https://github.com/whitesource-ft/ws-examples/pull/113)
=> Migrated the changes suggested by @tabac-ws in whitesource-ft PR 113

SAST/README.md, SAST/teamcity-mend_sast.yml
Migrated changes suggested by @tabac-ws in whitesource-ft [PR 114](https://github.com/whitesource-ft/ws-examples/pull/114)
=> Migrated changes suggested by tabac-ws in whitesource-ft PR 114

CI-CD/Bamboo/ws_scan.sh
@lukebrogan-mend added some env vars after testing it locally
=> Modify env vars for Bamboo

CI-CD/GitHub/github-action-lua.yml
add "build" block to LUA example
=> add "build" block to GH LUA example

CI-CD/Jenkins/Jenkins_pipeline_docker_scan.groovy
All file changes were copied from @tabac-ws [PR 96](https://github.com/whitesource-ft/ws-examples/pull/96) in whitesource-ft.
Changes should be reviewed individually
=> add jenkins docker scanning example

Prioritize/README.md
Update current example with a working script
=> Add ADO Prioritize logs and publish example

Prioritize/DotNet/Single-Module/azure-pipelines_linux-workshop.yml
This is required for Prioritize to run
=> Add .NET 3.1 to .NET workshop

CI-CD/AzureDevOps/azure-pipelines_dotnet_sbom.yml, CI-CD/AzureDevOps/azure-pipelines_maven.yml, CI-CD/AzureDevOps/azure-pipelines_npm.yml, CI-CD/Bitbucket/bitbucket-pipelines-npm.yml, CI-CD/CodeFresh/CodeFresh-NPM, CI-CD/GitHub/mend-ghaction-conan.yml, CI-CD/GitLab/gitlab-maven-cached-ua.yml, CI-CD/GitLab/gitlab-maven.yml, CI-CD/GitLab/gitlab-npm.yml, CI-CD/GitLab/gitlab-pip.yml, CI-CD/GoogleCloudBuild/cloud_build_npm.yaml, CI-CD/Jenkins/Jenkins_freestyle_maven.sh, CI-CD/Jenkins/Jenkins_pipeline_maven.groovy, CI-CD/Jenkins/Jenkins_pipeline_maven_multi-org.groovy, CI-CD/Jenkins/Jenkins_pipeline_npm.groovy
Tidhar,
As discussed, as best practice, added WS_FILESYSTEMSCAN=false when package managers are in place
=> Add filesystemscan=false when pkg mgrs are used

CI-CD/AzureDevOps/Azure-Pipelines_Windows_Maven, CI-CD/AzureDevOps/azure-pipelines_windows_maven
This is a template I created that will work on Windows-Latest agents in AZDO
=> Add Windows-Latest compatible YAML template for Java/Maven

Workshop/nodegoat/package.json after adding node-forge
Updated express to older version to show more Mend value.
=> Update package.json after adding node-forge

Unified Agent/Prioritize/Java/Single-Module/Gradle/github-action.yml
Caught this from a customer issue. Missing fi to end the if statement.
=> Fixing GH Action for Gradle Single Module

Repo-Integration/Self-Managed/README.md, Repo-Integration/Self-Managed/docker-compose.yaml, Repo-Integration/Self-Managed/setup.sh
Add version selection to repository integration to repo integration download and installation script.
Also added validation that the download is successful.
=> Add version selection to repo integration setup.sh script.

Repo-Integration/Self-Managed/certs.md
=> Clarify instructions

Repo-Integration/Self-Managed/certs.md
=> fix controller & remediate container cert path

Repo-Integration/Self-Managed/README.md, Repo-Integration/Self-Managed/docker-compose-sast.yaml, Repo-Integration/Self-Managed/setup.sh
Added docker-compose-sast.yaml and updated setup.sh to support GHE SAST self-managed repository integration automation scripts.
=> GHE SAST support for Self-Managed Repository Integration Automation Scripts is now available

Repo-Integration/Self-Managed/README.md
- Added steps for a fast setup in AWS EC2
- Added step to export Github token
- Updated Docker compose command for v2
=> Update README.md 

Repo-Integration/Self-Managed/README.md
Updates self-hosted Readme with a warning section at the top describing the behavior of Graylog healthchecks.
=> Updated Self-hosted Readme.md

Repo-Integration/Private-Registries-No-HostRules/Docker/config.js, Repo-Integration/Private-Registries-No-HostRules/Docker/docker-compose.yaml, Repo-Integration/Private-Registries-No-HostRules/Go/docker-compose.yaml, Repo-Integration/Private-Registries-No-HostRules/Gradle/Groovy/docker-compose.yaml, Repo-Integration/Private-Registries-No-HostRules/Gradle/Kotlin/docker-compose.yaml, Repo-Integration/Private-Registries-No-HostRules/Maven/config.js, Repo-Integration/Private-Registries-No-HostRules/Maven/docker-compose.yaml, Repo-Integration/Private-Registries-No-HostRules/NPM/docker-compose.yaml, Repo-Integration/Private-Registries-No-HostRules/NuGet/NuGet.Config, Repo-Integration/Private-Registries-No-HostRules/NuGet/docker-compose.yaml, Repo-Integration/Private-Registries-No-HostRules/PIP/docker-compose.yaml, Repo-Integration/Private-Registries-No-HostRules/README.md
- Adds Nuget
- Adds Docker
- Re-wrote documentation for ease-of-use.
Renames docker-compose.yaml files and makes them more uniform. Removes windows volume mapping paths.
=> Updates no host rules solution

Scripts/Mend SCA/get-malicious-packages.sh
This PR implements error handling for the get-malicious-packages.sh file.
=> Adds error handling for get-malicious-packages.sh script.

Repo-Integration/Silent-Onboarding/azure-repo-config.json, Repo-Integration/Silent-Onboarding/bitbucket-repo-config.json, Repo-Integration/Silent-Onboarding/github-repo-config.json, Repo-Integration/Silent-Onboarding/global-config.json
- Removed global-config.json as it is not needed
- Removed unnecessary parts of repo-config.json files
=> Fixed repo-config.json files

CI-CD/AzureDevOps/Mend CLI/AzureDevOps-Image-Scanning-linux.yaml, CI-CD/AzureDevOps/Mend CLI/AzureDevOps-Image-Scanning-windows.yaml, CI-CD/AzureDevOps/Mend CLI/AzureDevOps-advanced-linux.yml, CI-CD/AzureDevOps/Mend CLI/AzureDevOps-linux.yaml, CI-CD/AzureDevOps/Mend CLI/AzureDevOps-windows.yaml
Removes underscores from injected variables.
=> Updated Azure Devops Pipelines

CI-CD/AzureDevOps/Mend CLI/AzureDevOps-Image-Scanning-linux.yaml, CI-CD/AzureDevOps/Mend CLI/AzureDevOps-Image-Scanning-windows.yaml, CI-CD/GitHub/Mend CLI/Github_image_scan.yaml, CI-CD/GitLab/Mend CLI/gitlab_image_scan.yml
=> Add GH and GL image scanning

Scripts/Mend SCA/generate-async-report.sh
Update reportType to MEND_REPORTTYPE as the call was not performed
=> Update reportType to MEND_REPORTTYPE

Scripts/Mend SCA/README.md, Scripts/Mend SCA/check-project-state.sh
Removing UPDATE as a valid response to indicate completion. See:
https://mend-io.atlassian.net/wiki/spaces/DEV/pages/214630401/Get+Request+State+API+Call
Alerts need to be calculated before generating reports.
=> Removing UPDATE as a valid response to indicate completion

CI-CD/AzureDevOps/Mend CLI/AzureDevOps advanced linux with templates/AzureDevOps-advanced-linux-with-templates.yml, CI-CD/AzureDevOps/Mend CLI/AzureDevOps advanced linux with templates/README.md, CI-CD/AzureDevOps/Mend CLI/AzureDevOps advanced linux with templates/mend-reports-template.yml, CI-CD/AzureDevOps/Mend CLI/AzureDevOps advanced linux with templates/mend-scan-template.yml
=> Adding template-based ADO pipeline

CI-CD/Jenkins/Mend CLI/README.md
=> Fix jenkins doc

Scripts/Mend CN/README.md, Scripts/Mend CN/create-traceability-tags.sh
- Add Mend LABELS after FROM as without the image can't be built.
- Fix cURL download raw link
=> CN traceability script fix

Repo-Integration/Private-Registries-No-HostRules/Poetry/config.js, Repo-Integration/Private-Registries-No-HostRules/Poetry/docker-compose.yaml, Repo-Integration/Private-Registries-No-HostRules/README.md
Adds Poetry to the no host rules solution and updates documentation to explain how it works.
=> Adds Poetry to No host rules solution

Scripts/Mend SCA/README.md, Scripts/Mend SCA/get-all-policies.sh
=> Adds a script to get all policies from all levels of an organization

Repo-Integration/Private-Registries-No-HostRules/README.md, Repo-Integration/Private-Registries-No-HostRules/Ruby/config.js, Repo-Integration/Private-Registries-No-HostRules/Ruby/docker-compose.yaml
Adds an example for no hostrules for Ruby
=> Adds No-Host-Rule solution for Ruby

CI-CD/Jenkins/Mend CLI/README.md
=> fix: typo of README.md

Repo-Integration/Schemas/README.md, Repo-Integration/Schemas/ghc-integration-schema.json
Use the following URL for testing:
https://raw.githubusercontent.com/mend-toolkit/mend-examples/kyal/add-json-schema/Repo-Integration/Schemas/ghc-integration-schema.json
=> Added JSON Schemas for IDEs

Repo-Integration/Private-Registries-No-HostRules/Conda/.condarc, Repo-Integration/Private-Registries-No-HostRules/Conda/docker-compose.yaml, Repo-Integration/Private-Registries-No-HostRules/README.md
Adds no-host-rule information for conda.
=> Adds no-host-rule information for conda
